- src/Microsoft.Azure.Relay/WebSockets/ClientWebSocket45.cs
This buffer code was found in the .NET Reference Source.
> Including an update to ClientWebSocketOptions

- src/Microsoft.Azure.Relay/HybridConnectionClient.cs
- src/Microsoft.Azure.Relay/HybridConnectionListener.cs
- src/Microsoft.Azure.Relay/HybridConnectionRuntimeInformation.cs
- src/Microsoft.Azure.Relay/ManagementOperations.cs
- src/Microsoft.Azure.Relay/RelayConstants.cs
- src/Microsoft.Azure.Relay/Strings.Designer.cs
- src/Microsoft.Azure.Relay/Strings.resx
- src/Microsoft.Azure.Relay/project.json
Add HybridConnectionListener/HybridConnectionClient GetRuntimeInformationAsync() APIs implemented in terms of REST GET of the HybridConnectionDescription.
> Relay/HC: Add HybridConnection GetRuntimeInformationAsync() APIs

- src/Microsoft.Azure.Relay/project.json
> Update version in project.json

- src/Microsoft.Azure.Relay/project.json
Updating for next version 0.1.2-preview
> Update project.json - 0.1.2-preview

- appveyor.yml
- test/Microsoft.Azure.Relay.UnitTests/RunTimeTests.cs
- test/Microsoft.Azure.Relay.UnitTests/SasKeyGenerator.cs
- test/Microsoft.Azure.Relay.UnitTests/project.json
> Run unit tests on .NET Core

- src/Microsoft.Azure.Relay/Common/InputQueue.cs
- src/Microsoft.Azure.Relay/Common/TaskEx.cs
- src/Microsoft.Azure.Relay/Common/TrackingContext.cs
- src/Microsoft.Azure.Relay/HybridConnectionClient.cs
- src/Microsoft.Azure.Relay/HybridConnectionConstants.cs
- src/Microsoft.Azure.Relay/HybridConnectionListener.cs
- src/Microsoft.Azure.Relay/HybridConnectionStream.cs
- src/Microsoft.Azure.Relay/ListenerCommand.cs
- src/Microsoft.Azure.Relay/RelayConnectionStringBuilder.cs
- src/Microsoft.Azure.Relay/RelayEventSource.cs
- src/Microsoft.Azure.Relay/RelayedHttpListenerContext.cs
- src/Microsoft.Azure.Relay/RelayedHttpListenerRequest.cs
- src/Microsoft.Azure.Relay/RelayedHttpListenerResponse.cs
- src/Microsoft.Azure.Relay/Strings.Designer.cs
- src/Microsoft.Azure.Relay/Strings.resx
- src/Microsoft.Azure.Relay/System/Net/HttpStatusDescription.cs
- src/Microsoft.Azure.Relay/TokenRenewer.cs
- src/Microsoft.Azure.Relay/WebSocketStream.cs
- test/Microsoft.Azure.Relay.UnitTests/RunTimeTests.cs
> HybridConnectionListener.AcceptHandler feature

- src/Microsoft.Azure.Relay/Common/ActionItem.cs
- src/Microsoft.Azure.Relay/Common/InputQueue.cs
- src/Microsoft.Azure.Relay/WebSockets/Net45/Logging.cs
- src/Microsoft.Azure.Relay/project.json
Don't use Thread or ThreadPool classes.  Use alternative APIs which exist in Full .NET, .NET Core, and UWP.  Addresses issue https://github.com/Azure/azure-relay-dotnet/issues/36
> UWP doesn't support Thread or ThreadPool.

- src/Microsoft.Azure.Relay/RelayedHttpListenerContext.cs
- src/Microsoft.Azure.Relay/WebSockets/NetCore/HttpKnownHeaderNames.cs
- src/Microsoft.Azure.Relay/WebSockets/NetCore/ManagedWebSocket.cs
- src/Microsoft.Azure.Relay/WebSockets/NetCore/NetEventSource.WebSockets.cs
- src/Microsoft.Azure.Relay/WebSockets/NetCore/SR.cs
- src/Microsoft.Azure.Relay/WebSockets/NetCore/WebSocketHandle.Managed.cs
- src/Microsoft.Azure.Relay/WebSockets/NetCore/WebSocketValidate.cs
- src/Microsoft.Azure.Relay/project.json
Integrate the copied ClientWebSocket and related files from .NET Core.
> Pull in latest changes to the copy of .NET Core's ClientWebSocket.

- test/Microsoft.Azure.Relay.UnitTests/RunTimeTests.cs
This turns out to be a test issue: the test is written so that it attempts to send the entire payload before even starting to receive anything on the other side of the conversation.  The fix is to send and receive in parallel to allow for streaming of the data.
> Fix for WriteLargeDataSetTest failures

- src/Microsoft.Azure.Relay/WebSocketExceptionHelper.cs
- test/Microsoft.Azure.Relay.UnitTests/RunTimeTests.cs
Return EndpointNotFoundException in that case as well.
> Update the exception handling code to understand name resolution failure

- src/Microsoft.Azure.Relay/AuthorizationFailedException.cs
- src/Microsoft.Azure.Relay/Common/SecurityToken.cs
- src/Microsoft.Azure.Relay/Common/TokenProvider.cs
- src/Microsoft.Azure.Relay/ConnectionLostException.cs
- src/Microsoft.Azure.Relay/EndpointAlreadyExistsException.cs
- src/Microsoft.Azure.Relay/EndpointNotFoundException.cs
- src/Microsoft.Azure.Relay/HybridConnectionClient.cs
- src/Microsoft.Azure.Relay/HybridConnectionListener.cs
- src/Microsoft.Azure.Relay/HybridConnectionStream.cs
- src/Microsoft.Azure.Relay/QuotaExceededException.cs
- src/Microsoft.Azure.Relay/RelayException.cs
- src/Microsoft.Azure.Relay/ServerBusyException.cs
- src/Microsoft.Azure.Relay/WebSocketExceptionHelper.cs
- Update missing Xml Documentation for some parameters.
- Remove some dead code in SecurityToken.
- Don't wrap RelayException or TimeoutException with another RelayException.
- HybridConnectionListener: if a disconnect occurs and EndpointNotFoundException happens on reconnect then the listener should go Offline (stop reconnecting).
- HybridConnectionListener: When the listener goes completely Offline don't overwrite the LastError, if any.
> Integrate changes from the internal/service repo:

- src/Microsoft.Azure.Relay/WebSockets/NetCore/AuthenticationHelper.Digest.cs
- src/Microsoft.Azure.Relay/WebSockets/NetCore/AuthenticationHelper.cs
- src/Microsoft.Azure.Relay/WebSockets/NetCore/StringBuilderCache.cs
- src/Microsoft.Azure.Relay/WebSockets/NetCore/WebSocketHandle.Managed.cs
[These changes come from @Priya91's Priya91:proxy branch, however the team's not ready to update the build system yet. For this reason this PR includes only the C# files and skips updating the project.json to *cs.proj.]
With this PR, before attempting to open a connection to the host, if there is a proxy specified, which is not the DefaultWebProxy, in ClientWebSocketOptions, then this change tries to establish the connection via the proxy.
Proxy servers that support basic and digest auth are supported.
If the proxy wants to send a response body then that is also read from the stream, only when the content-length header is specified. Chunked content from proxies is not supported.
> Implement proxies for clientwebsocket. Don't change build files yet.

- src/Microsoft.Azure.Relay/Common/TrackingContext.cs
- src/Microsoft.Azure.Relay/HybridConnectionListener.cs
- src/Microsoft.Azure.Relay/HybridConnectionStream.cs
- src/Microsoft.Azure.Relay/HybridConnectionUtility.cs
- src/Microsoft.Azure.Relay/RelayEventSource.cs
- src/Microsoft.Azure.Relay/RelayedHttpListenerContext.cs
Make TrackingContext public on HybridConnectionListener, HybridConnectionStream, and RelayedHttpListenerContext.
Addresses #65 
> Make TrackingContext public

- src/Microsoft.Azure.Relay/Microsoft.Azure.Relay.csproj
Update nuget package version for new build/release.
> Update nuget package version for new build/release.

- src/Microsoft.Azure.Relay/AuthorizationFailedException.cs
- src/Microsoft.Azure.Relay/Common/InputQueue.cs
- src/Microsoft.Azure.Relay/ConnectionLostException.cs
- src/Microsoft.Azure.Relay/EndpointAlreadyExistsException.cs
- src/Microsoft.Azure.Relay/EndpointNotFoundException.cs
- src/Microsoft.Azure.Relay/HybridConnectionRuntimeInformation.cs
- src/Microsoft.Azure.Relay/Microsoft.Azure.Relay.csproj
- src/Microsoft.Azure.Relay/QuotaExceededException.cs
- src/Microsoft.Azure.Relay/RelayException.cs
- src/Microsoft.Azure.Relay/ServerBusyException.cs
- test/Microsoft.Azure.Relay.UnitTests/HybridConnectionTestBase.cs
- test/Microsoft.Azure.Relay.UnitTests/Microsoft.Azure.Relay.UnitTests.csproj
Update Microsoft.Azure.Relay to target netstandard2.0.
> Move the projects to use netstandard2.0/netcoreapp2.0.

- src/Microsoft.Azure.Relay/WebSockets/NetCore/WebSocketHandle.Managed.cs
> Bug: Check if proxy uri is not null.

- src/Microsoft.Azure.Relay/Strings.Designer.cs
- src/Microsoft.Azure.Relay/Strings.resx
- src/Microsoft.Azure.Relay/WebSockets/NetCore/WebSocketHandle.Managed.cs
> Check for proxy credentials being null.

- src/Microsoft.Azure.Relay/Common/AsyncLock.cs
- src/Microsoft.Azure.Relay/Common/InputQueue.cs
- src/Microsoft.Azure.Relay/Common/SecurityToken.cs
- src/Microsoft.Azure.Relay/Common/SharedAccessSignatureTokenProvider.cs
- src/Microsoft.Azure.Relay/Common/TimeoutHelper.cs
Some suggested code clean ups.
> Suggested Code Cleanups

- .github/CONTRIBUTING.md
Adding some guidelines from .NET Core FX about not submitting PRs just to update things to new language features or change the code style.
> Adding guidelines from .NET Core about superfluous changes

- src/Microsoft.Azure.Relay/Common/AsyncLock.cs
- src/Microsoft.Azure.Relay/Common/InputQueue.cs
- src/Microsoft.Azure.Relay/Common/SecurityToken.cs
- src/Microsoft.Azure.Relay/Common/TimeoutHelper.cs
- src/Microsoft.Azure.Relay/Common/TrackingContext.cs
- src/Microsoft.Azure.Relay/EndpointNotFoundException.cs
- src/Microsoft.Azure.Relay/HybridConnectionClient.cs
- src/Microsoft.Azure.Relay/HybridConnectionConstants.cs
- src/Microsoft.Azure.Relay/HybridConnectionListener.cs
- src/Microsoft.Azure.Relay/HybridConnectionRuntimeInformation.cs
- src/Microsoft.Azure.Relay/HybridConnectionUtility.cs
- src/Microsoft.Azure.Relay/HybridHttpConnection.cs
- src/Microsoft.Azure.Relay/ListenerCommand.cs
- src/Microsoft.Azure.Relay/RelayedHttpListenerRequest.cs
- src/Microsoft.Azure.Relay/RelayedHttpListenerResponse.cs
- src/Microsoft.Azure.Relay/TokenRenewer.cs
- src/Microsoft.Azure.Relay/WebSocketExceptionHelper.cs
- src/Microsoft.Azure.Relay/WebSocketStream.cs
- test/Microsoft.Azure.Relay.UnitTests/ExceptionExtensions.cs
- test/Microsoft.Azure.Relay.UnitTests/RunTimeTests.cs
Integrate changes from internal repo to GitHub repo.
The changes in HybridHttpConnection.cs address #80.
> Integrate changes from internal repo to GitHub repo.

- README.md
The link to the samples was broken.
> Readme.md: Fix Broken Link

- Microsoft.Azure.Relay.sln
- src/Microsoft.Azure.Relay/Microsoft.Azure.Relay.csproj
Microsoft.Azure.Relay.csproj:
- Add Copyright.
- Add a few more package tags.
Microsoft.Azure.Relay.sln:
- Include some of the non-C# files in to the solution for easy access.
> Solution and Project Updates

- src/Microsoft.Azure.Relay/Microsoft.Azure.Relay.csproj
Updating version number to 2.0.0 in preparation for release.
> Updating version number in preparation for release.

- src/Microsoft.Azure.Relay/HybridConnectionListener.cs
Include more comments about the IConnectionStatus event handling
> Include more comments about the IConnectionStatus event handling

- test/Microsoft.Azure.Relay.UnitTests/DisplayTestNameAttribute.cs
- test/Microsoft.Azure.Relay.UnitTests/HybridRequestTests.cs
- test/Microsoft.Azure.Relay.UnitTests/Microsoft.Azure.Relay.UnitTests.csproj
- test/Microsoft.Azure.Relay.UnitTests/TestUtility.cs
Add a unit test for performance/scale testing.
> Add a unit test for performance/scale testing.

- src/Microsoft.Azure.Relay/Common/AsyncLock.cs
- src/Microsoft.Azure.Relay/Common/Fx.cs
- src/Microsoft.Azure.Relay/Common/PlatformHelpers.cs
- src/Microsoft.Azure.Relay/HybridConnectionUtility.cs
- src/Microsoft.Azure.Relay/HybridHttpConnection.cs
- src/Microsoft.Azure.Relay/Microsoft.Azure.Relay.csproj
- src/Microsoft.Azure.Relay/WebSocketMessageStream.cs
- src/Microsoft.Azure.Relay/WebSocketStream.cs
- test/Microsoft.Azure.Relay.UnitTests/Microsoft.Azure.Relay.UnitTests.csproj
Fixup versioning macros to use the built in ones
> Fixup versioning macros to use the built in ones

- src/Microsoft.Azure.Relay/Common/PlatformHelpers.cs
- src/Microsoft.Azure.Relay/HybridConnectionConstants.cs
Pass more client version details: OS Version and .NET Runtime description
> Pass more client version details: OS Version and .NET Runtime description

- .github/workflows/pr_build.yml
- test/Microsoft.Azure.Relay.UnitTests/Constants.cs
- test/Microsoft.Azure.Relay.UnitTests/HybridConnectionTestBase.cs
This needs an additional change to also check this env variable name but I can't do that in the portal, will do it as a second commit.
> Dlstucki test patch 1

- src/Microsoft.Azure.Relay/HybridConnectionListener.cs
- src/Microsoft.Azure.Relay/TokenRenewer.cs
- Merged PR: Avoid System.ArgumentOutOfRangeException on token refresh interval
- Merged PR: Fire and forget HybridConnection accept handler
> Integrate changes from internal service repo

- NuGet.config
Remove the multiple nuget feed vulnerability.
> Remove the multiple nuget feed vulnerability.

- src/Microsoft.Azure.Relay/ClientWebSocketFactory.cs
- src/Microsoft.Azure.Relay/HybridConnectionClient.cs
- src/Microsoft.Azure.Relay/HybridConnectionListener.cs
- src/Microsoft.Azure.Relay/HybridHttpConnection.cs
- src/Microsoft.Azure.Relay/RelayedHttpListenerContext.cs
- test/Microsoft.Azure.Relay.UnitTests/CustomClientWebSocketFactory.cs
- test/Microsoft.Azure.Relay.UnitTests/WebSocketTests.cs
> Add support for injecting custom web socket implementation.

- src/Microsoft.Azure.Relay/ClientWebSocketFactory.cs
- src/Microsoft.Azure.Relay/HybridConnectionClient.cs
- src/Microsoft.Azure.Relay/HybridConnectionListener.cs
- src/Microsoft.Azure.Relay/HybridHttpConnection.cs
- src/Microsoft.Azure.Relay/RelayedHttpListenerContext.cs
- test/Microsoft.Azure.Relay.UnitTests/CustomClientWebSocketFactory.cs
- test/Microsoft.Azure.Relay.UnitTests/WebSocketTests.cs
> Updating master from dev

- .pipelines/pipeline.user.windows.yml
- .version/PipelineAssemblyInfo.cs
- Microsoft.Azure.Relay.sln
- package.cmd
- package.sh
- src/Microsoft.Azure.Relay/Common/AzureActiveDirectoryTokenProvider.cs
- src/Microsoft.Azure.Relay/Common/JsonSecurityToken.cs
- src/Microsoft.Azure.Relay/Common/ManagedIdentityTokenProvider.cs
- src/Microsoft.Azure.Relay/Common/PlatformHelpers.cs
- src/Microsoft.Azure.Relay/Common/SecurityToken.cs
- src/Microsoft.Azure.Relay/Common/SharedAccessSignatureTokenProvider.cs
- src/Microsoft.Azure.Relay/Common/TokenProvider.cs
- src/Microsoft.Azure.Relay/HybridConnectionClient.cs
- src/Microsoft.Azure.Relay/HybridConnectionConstants.cs
- src/Microsoft.Azure.Relay/HybridConnectionListener.cs
- src/Microsoft.Azure.Relay/HybridConnectionUtility.cs
- src/Microsoft.Azure.Relay/HybridHttpConnection.cs
- src/Microsoft.Azure.Relay/Microsoft.Azure.Relay.csproj
- src/Microsoft.Azure.Relay/RelayConnectionStringBuilder.cs
- src/Microsoft.Azure.Relay/Strings.Designer.cs
- src/Microsoft.Azure.Relay/Strings.resx
- src/Microsoft.Azure.Relay/WebSocketMessageStream.cs
- src/Microsoft.Azure.Relay/WebSocketStream.cs
- test/Directory.Build.props
- test/Microsoft.Azure.Relay.UnitTests/ConnectionStringBuilderTests.cs
- test/Microsoft.Azure.Relay.UnitTests/HybridConnectionTestBase.cs
- versioning.cmd
- versioning.ps1
- Added new TokenProvider types to support RBAC authentication
- Added new SecurityToken type to support RBAC authentication
- Modified RelayConnectionStringBuilder to be able to accept "Authentication=ManagedIdentity" as part of the connection string to automatically adapt a ManagedIdentityTokenProvider as the authentication choice
- Changed SecurityToken class to be abstract (breaking change)
- Incremented package version to 3.0.0-Preview
- Changed target framework version to net461
> Implementations for Relay RBAC and bump version to 3.0.0-Preview
